First_Website/App1/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("A", views.A, name="A"),
    path("B", views.B, name="B"),
]

First_Website/First_Website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("App1.urls")),
    path('tasks/', include("tasks.urls")),
    path('New_Year/', include("New_Year.urls")),
]

First_Website/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

First_Website/App1/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "App1/index.html")

def A(request):
    return HttpResponse("Hello, A!")

def B(request):
    return HttpResponse("Hello, B!")

def greet(request, name):
    return render(request, "App1/greet.html", {
        "name": name.capitalize()
    })

First_Website/New_Year/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "New_Year/index.html", {
        "New_Year": now.month == 1 and now.day == 1
    })

First_Website/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task.")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

First_Website/App1/templates/App1/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

First_Website/App1/templates/App1/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, world!</h1>
    </body>
</html>

First_Website/New_Year/templates/New_Year/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it the New Year?</title>
        <link href="{% static 'newYR/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if New_Year %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

First_Website/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }} 
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View all tasks.</a>
{% endblock %}

First_Website/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <l1>No tasks yet.</l1>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a new task.</a>
{% endblock %}

First_Website/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>